CREATE TABLE Roles(
	Id BIGINT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(50)
    )

CREATE TABLE Users (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) UNIQUE,
    PasswordHash VARCHAR(255),
    RoleId BIGINT,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Address VARCHAR(50),
    PhoneNumber VARCHAR(50),
    Email VARCHAR(50),
	FOREIGN KEY (RoleId) REFERENCES Roles(Id)
)

CREATE TABLE Categories (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50)
)

CREATE TABLE Items (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
	Status VARCHAR(20),
    CategoryId BIGINT,
    DiscountId BIGINT NULL,
    Type VARCHAR(50),
    Title VARCHAR(50),
    Description VARCHAR(1023),
	Quantity INT, CHECK (Quantity > 0),
    Price FLOAT, CHECK (Price > 0),
    FOREIGN KEY (CategoryId) REFERENCES Categories(Id) ON DELETE SET NULL)

CREATE TABLE Owns (
	UserId BIGINT,
	ItemId BIGINT UNIQUE,
	FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
	FOREIGN KEY (ItemId) REFERENCES Items(Id) ON DELETE CASCADE
)

CREATE TABLE Discounts (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    ItemId BIGINT,
    Percentage INT, CHECK (Percentage >= 0 AND Percentage <= 100),
    UserId BIGINT,
    FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (ItemId) REFERENCES Items(Id)
)

CREATE TABLE UserItems (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    UserId BIGINT,
    ItemId BIGINT,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (ItemId) REFERENCES Items(Id) ON DELETE CASCADE
)

CREATE TABLE WishedUserItems (
	Id BIGINT PRIMARY KEY AUTO_INCREMENT,
	UserId BIGINT,
	ItemId BIGINT,
	FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
	FOREIGN KEY (ItemId) REFERENCES Items(Id) ON DELETE CASCADE
)

CREATE TABLE Orders (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Price FLOAT, CHECK (Price>0),
    OrderedAt TIMESTAMP,
    Type VARCHAR(50),
    DeliveryDataId BIGINT
)

CREATE TABLE Ordered(
	UserId BIGINT,
	OrderId BIGINT UNIQUE,
	FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
	FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE
)

CREATE TABLE DeliveryDatas (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Address VARCHAR(50),
    Type VARCHAR(50),
    OrderId BIGINT,
    UserId BIGINT,
    FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
)

CREATE TABLE OrderItems (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    OrderId BIGINT,
    ItemId BIGINT,
    FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE,
    FOREIGN KEY (ItemId) REFERENCES Items(Id)
    )